// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sentinel;

#nullable disable

namespace Sentinel.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    partial class SentinelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Sentinel.Models.Db.AppBinary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppBinaryBaseDirId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppBinaryBaseDirId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("Path");

                    b.ToTable("AppBinaries");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AppBinaryBaseDir", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Path");

                    b.ToTable("AppBinaryBaseDirs");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AppBinaryFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppBinaryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppBinaryId");

                    b.HasIndex("Path");

                    b.ToTable("AppBinaryFiles");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AppBinaryFileChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppBinaryFileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OffsetBytes")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppBinaryFileId");

                    b.ToTable("AppBinaryFileChunks");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AppBinary", b =>
                {
                    b.HasOne("Sentinel.Models.Db.AppBinaryBaseDir", "AppBinaryBaseDir")
                        .WithMany()
                        .HasForeignKey("AppBinaryBaseDirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppBinaryBaseDir");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AppBinaryFile", b =>
                {
                    b.HasOne("Sentinel.Models.Db.AppBinary", "AppBinary")
                        .WithMany("Files")
                        .HasForeignKey("AppBinaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppBinary");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AppBinaryFileChunk", b =>
                {
                    b.HasOne("Sentinel.Models.Db.AppBinaryFile", "AppBinaryFile")
                        .WithMany("Chunks")
                        .HasForeignKey("AppBinaryFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppBinaryFile");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AppBinary", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Sentinel.Models.Db.AppBinaryFile", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
